### ISSUE TITLE
TensorFlow GPU Job RUNING ERROR

### ISSUE THREAD

**Issue by bleachzk** [IBM/FfDL#127]
FfDL Version：0.1
TensorFlow Version：1.5.0-gpu-py3

I try to run a job get error as here：

`132 | 1534166953114 | pciBusID: 0000:00:06.0
-- | -- | --
133 | 1534166953115 | totalMemory: 22.40GiB freeMemory: 22.29GiB
134 | 1534166953116 | 2018-08-13 13:29:02.319076: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla M40 24GB, pci bus id: 0000:00:06.0, compute capability: 5.2)
135 | 1534166953117 | /usr/local/bin/train.sh: line 18:    36 Killed                  python3 convolutional_network.py --trainImagesFile ${DATA_DIR}/train-images-idx3-ubyte.gz --trainLabelsFile ${DATA_DIR}/train-labels-idx1-ubyte.gz --testImagesFile ${DATA_DIR}/t10k-images-idx3-ubyte.gz --testLabelsFile ${DATA_DIR}/t10k-labels-idx1-ubyte.gz --learningRate 0.001 --trainingIters 2000 2>&1
136 | 1534166953118 | Training process finished. Exit code: 137
137 | 1534166953119 | Job exited with error code 137
138 | 1534166953120 | Failed: learner_exit_code: 137`

**Comment by Tomcli** [comment]
Hi @bleachzk , it looks like the learner pod didn't have enough memory to run this job using GPU. For this MNIST example, we recommend to allocate at least 2GB of memory per learner pod. An example manifest is available at https://github.com/IBM/FfDL/blob/master/etc/examples/tf-model/gpu-manifest.yml
```yaml
name: tf_convolutional_network_tutorial
description: Convolutional network model using tensorflow
version: "1.0"
gpus: 1
cpus: 2
memory: 2Gb

# Object stores that allow the system to retrieve training data.
data_stores:
  - id: sl-internal-os
    type: mount_cos
    training_data:
      container: tf_training_data
    training_results:
      container: tf_trained_model
    connection:
      auth_url: http://s3.default.svc.cluster.local
      user_name: test
      password: test

framework:
  name: tensorflow
  version: "1.5.0-gpu-py3"
  command: >
    python3 convolutional_network.py --trainImagesFile ${DATA_DIR}/train-images-idx3-ubyte.gz
      --trainLabelsFile ${DATA_DIR}/train-labels-idx1-ubyte.gz --testImagesFile ${DATA_DIR}/t10k-images-idx3-ubyte.gz
      --testLabelsFile ${DATA_DIR}/t10k-labels-idx1-ubyte.gz --learningRate 0.001
      --trainingIters 20000
evaluation_metrics:
  type: tensorboard
  in: "$JOB_STATE_DIR/logs/tb"
  # (Eventual) Available event types: 'images', 'distributions', 'histograms', 'images'
  # 'audio', 'scalars', 'tensors', 'graph', 'meta_graph', 'run_metadata'
  #  event_types: [scalars]
```
