### ISSUE TITLE
how to use pytorch and caffe built by ourselves？

### ISSUE THREAD

**Issue by Eric-Zhang1990** [IBM/FfDL#160]
@animeshsingh  Can you tell me how to use framework like pytorch and caffe built by ourselves? Thanks very much!

**Comment by Tomcli** [comment]
Hi @Eric-Zhang1990. To use your own framework in FfDL, simply change the framework fields in your manifest file.
```yaml
framework:
  name: custom
  version: "docker.io/namespace/imagename:version"
  command: <Your entrypoint command>
```
